[versions]
agp = "8.0.1"
api = "82"

[libraries]
api = { module = "de.robv.android.xposed:api", version.ref = "api" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }